# This workflow builds a Java .war file and uploads it as an artifact.
name: Reusable Java WAR Build
on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '17'
      artifact-name:
        type: string
        required: true
      runner-label:
        type: string
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner-label }}
    steps:
      - name: 1. Setup Java/Maven Environment
        # Use the full path to the action in this repo, with a ref (e.g., @main)
        uses: PoC-Pipeline-Conversion-Jenkins-GHA/cicd-template/.github/actions/setup-java-maven@main
        with:
          java-version: ${{ inputs.java-version }}
          checkout-code: 'true'

      - name: 2. Build WAR with Maven
        run: mvn -B clean package -DskipTests=true

      - name: 3. Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          # Upload only the .war file(s) from the target directory
          path: target/*.war
          retention-days: 7
